tg:
  apiId:
  apiHash:
  userPhone:
  adminId:
  enable: true
proxy:
  enable: false
  host: 127.0.0.1
  type: socks5
  port: 7890

ql:
  url: http://127.0.0.1:8090
  client-id: aaaa
  client-secret: aaaa

notify:
  bark-url:
  enable: false
  group: 京东监控

spring:
  profiles:
    active: dev

monitor:
  data-url: https://file.fanlisky.cn/d/share/env.json
  channel:
    - -1001670294604